import Foundation
import SwiftUI

public extension Color {
    static let bgChip = Color("bgChip", bundle: .module)
    static let bgEllipsis = Color("bgEllipsis", bundle: .module)
    static let bgG100 = Color("bgG100", bundle: .module)
    static let bgG200 = Color("bgG200", bundle: .module)
    static let bgG50 = Color("bgG50", bundle: .module)
    static let bgG75 = Color("bgG75", bundle: .module)
    static let bgPencil = Color("bgPencil", bundle: .module)
    static let bgG100 = Color("bgG100", bundle: .module)
    static let bgG200 = Color("bgG200", bundle: .module)
    static let bgG50 = Color("bgG50", bundle: .module)
    static let bgWhite = Color("bgWhite", bundle: .module)
    static let bgYellow = Color("bgYellow", bundle: .module)
    static let borderG300 = Color("borderG300", bundle: .module)
    static let borderG400 = Color("borderG400", bundle: .module)
    static let borderG500 = Color("borderG500", bundle: .module)
    static let borderR100 = Color("borderR100", bundle: .module)
    static let iconG600 = Color("iconG600", bundle: .module)
    static let iconG800 = Color("iconG800", bundle: .module)
    static let primaryGray = Color("primaryGray", bundle: .module)
    static let primaryHambugRed = Color("primaryHambugRed", bundle: .module)
    static let secondaryBrown = Color("secondaryBrown", bundle: .module)
    static let secondaryGreen = Color("secondaryGreen", bundle: .module)
    static let secondaryOrange = Color("secondaryOrange", bundle: .module)
    static let secondaryYellow = Color("secondaryYellow", bundle: .module)
    static let textG600 = Color("textG600", bundle: .module)
    static let textG800 = Color("textG800", bundle: .module)
    static let textG900 = Color("textG900", bundle: .module)
    static let textR100 = Color("textR100", bundle: .module)
}
